config:
  selfUrl: # https://saas.locpoc.dev
  corsOrigins: https://locpoc-st-gateway-web,https://locpoc-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://locpoc-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.locpoc.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.locpoc.dev
  tlsSecret: locpoc-tls

image:
  repository: sts/locpoc-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      