config:
  selfUrl: # https://gateway-web.locpoc.dev
  corsOrigins: # https://locpoc-st-angular
  globalConfigurationBaseUrl: # http://locpoc-st-gateway-web
  authServer:
    authority: # http://locpoc-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.locpoc.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #
  
reRoutes:
  accountService:
    url: http://locpoc-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://locpoc-st-administration
  identityService:
    url: http://locpoc-st-identity
  productService:
    url: http://locpoc-st-product
ingress:
  host: # gateway-web.locpoc.dev
  tlsSecret: locpoc-tls

image:
  repository: sts/locpoc-gateway-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}