config:
  selfUrl: # https://product.locpoc.dev
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://locpoc-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.locpoc.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: product.locpoc.dev
  tlsSecret: locpoc-tls

image:
  repository: sts/locpoc-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      